### ISSUE TITLE
Have you finished this repo?

### ISSUE THREAD

**Issue by 943fansi** [StephanAkkerman/Crypto_Forecasting#11]
@StephanAkkerman Hi, I am very interested with your work. Is it possible to see your thesis? It is cool to consider the volatility characteristics of time series in prediction models.

**Comment by StephanAkkerman** [comment]
Hi, thanks for showing interest in this project. Unfortunately, my thesis is not yet done, I plan to finish it around October so around that time I am able to share it with you. I will update the readme to add some more information for other interested people

**Comment by 943fansi** [comment]
@StephanAkkerman Thank you for your reply and wish you all the best.

**Comment by StephanAkkerman** [comment]
@943fansi It is done! The thesis is not yet publicly available, it will be added as a link once it's available online.
