### ISSUE TITLE
ValueError: None is not in list

### ISSUE THREAD

**Issue by Alex1996-alt** [StephanAkkerman/Crypto_Forecasting#54]
Hey, I’m running the code on a new system and encountering an error while executing hyperopt_ray.py (see screenshot). Do you have any idea what might be causing this and how to fix it? Thank you for your time!
![image](https://github.com/user-attachments/assets/21155630-64fa-4187-8984-fbbfb9ec9bf6)

**Comment by StephanAkkerman** [comment]
Thanks for the report, it's fixed now

**Comment by Alex1996-alt** [comment]
Hi thanks for your time. Getting now this error 
![image](https://github.com/user-attachments/assets/4e8784fe-957a-4664-b0ba-1d184804d99d)

**Comment by StephanAkkerman** [comment]
It's fixed now, I don't have time yet to run the full hyperopt code so I hope there are not many other bugs down the line

**Comment by Alex1996-alt** [comment]
Hi all right no problem so far everything seems to be working. A question of understanding where exactly in the code the P-values from Mann-Whitney U test for Autocorrelation are calculated/generated?

**Comment by StephanAkkerman** [comment]
The code for the Mann-Whitney U test can be found here: https://github.com/StephanAkkerman/crypto-forecasting-benchmark/blob/main/src/experiment/data_properties.py#L96

And the function that uses that for the autocorrelation is found here: https://github.com/StephanAkkerman/crypto-forecasting-benchmark/blob/main/src/experiment/data_properties.py#L160

**Comment by Alex1996-alt** [comment]
Thank you
